import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class DBApp {
    private JTextField textField1;
    private JTextField textField2;
    private JTextArea textArea1;
    private JButton button1;
    private JButton button2;

// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!

    public DBApp() {
        $$$setupUI$$$();
    }

    public static void main(String[] args) {

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setName("MovieDB");
        panel1.setBorder(BorderFactory.createTitledBorder(null, "MovieDB", TitledBorder.CENTER, TitledBorder.ABOVE_TOP));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        scrollPane1.setMaximumSize(new Dimension(150, 400));
        scrollPane1.setMinimumSize(new Dimension(150, 400));
        scrollPane1.setName("Genres");
        scrollPane1.setPreferredSize(new Dimension(150, 400));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        panel1.add(scrollPane1, gbc);
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "Genres", TitledBorder.CENTER, TitledBorder.TOP, new Font(scrollPane1.getFont().getName(), scrollPane1.getFont().getStyle(), scrollPane1.getFont().getSize())));
        final JScrollPane scrollPane2 = new JScrollPane();
        scrollPane2.setMaximumSize(new Dimension(150, 400));
        scrollPane2.setMinimumSize(new Dimension(150, 400));
        scrollPane2.setName("Countries");
        scrollPane2.setPreferredSize(new Dimension(150, 400));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        panel1.add(scrollPane2, gbc);
        scrollPane2.setBorder(BorderFactory.createTitledBorder(null, "Countries", TitledBorder.CENTER, TitledBorder.TOP));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setMaximumSize(new Dimension(150, 400));
        panel2.setMinimumSize(new Dimension(150, 400));
        panel2.setName("Cast");
        panel2.setPreferredSize(new Dimension(150, 400));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        panel1.add(panel2, gbc);
        panel2.setBorder(BorderFactory.createTitledBorder(null, "Cast", TitledBorder.CENTER, TitledBorder.TOP));
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(textField1, gbc);
        textField2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(textField2, gbc);
        textArea1 = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(textArea1, gbc);
        button1 = new JButton();
        button1.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(button1, gbc);
        button2 = new JButton();
        button2.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(button2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel3.setMaximumSize(new Dimension(150, 400));
        panel3.setMinimumSize(new Dimension(150, 400));
        panel3.setName("Rating");
        panel3.setPreferredSize(new Dimension(150, 400));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        panel1.add(panel3, gbc);
        panel3.setBorder(BorderFactory.createTitledBorder(null, "Rating", TitledBorder.CENTER, TitledBorder.TOP));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel4.setMaximumSize(new Dimension(150, 200));
        panel4.setMinimumSize(new Dimension(150, 200));
        panel4.setName("TagsRatings");
        panel4.setPreferredSize(new Dimension(150, 200));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel4, gbc);
        panel4.setBorder(BorderFactory.createTitledBorder(null, "Users' Tags/Ratings", TitledBorder.CENTER, TitledBorder.TOP, new Font(panel4.getFont().getName(), panel4.getFont().getStyle(), panel4.getFont().getSize())));
    }
}
